const rdmInventory = [
  {
    s: "Section 527",
    r: "16",
    q: "4",
    p: "219",
    i: "VB11651371155",
    d: "527",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Section 527",
    g: "0",
    e: "0",
    h: "03/14/25",
    t: "2",
    v: "2,4",
    c: "318536",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "196.30",
    mar: false,
    integrated: false,
    bid: "26740",
    dsc: "28.80",
    ls: "",
    hs: "",
    faceValue: "0.00",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "228.66",
      aip: "280.54",
      dsc: "41.16",
      faceValue: "0.00",
    },
    op: 160,
    b: 62,
    pOrig: "219",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 288,
    rdRowNumConverted: 16,
    rdBasePrice: 160,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Section 523",
    r: "15",
    q: "4",
    p: "239",
    i: "VB11691725897",
    d: "523",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Section 523",
    g: "0",
    e: "0",
    h: "03/14/25",
    t: "2",
    v: "2,4",
    c: "318536",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "218.72",
    mar: false,
    integrated: false,
    bid: "24409",
    dsc: "32.22",
    ls: "",
    hs: "",
    faceValue: "106.70",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "255.82",
      aip: "312.58",
      dsc: "46.05",
      faceValue: "152.49",
    },
    op: 179,
    b: 67,
    pOrig: "239",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 313.25,
    rdRowNumConverted: 15,
    rdBasePrice: 179,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Section 536",
    r: "7",
    q: "4",
    p: "269",
    i: "VB11039856107",
    d: "536",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Section 536",
    g: "0",
    e: "0",
    h: "03/13/25",
    t: "0",
    v: "2,4",
    c: "318536",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "243.50",
    mar: false,
    integrated: false,
    bid: "23838",
    dsc: "36.00",
    ls: "10",
    hs: "13",
    faceValue: "130.85",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "285.83",
      aip: "348.00",
      dsc: "51.45",
      faceValue: "187.00",
    },
    op: 200,
    b: 76,
    pOrig: "269",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 270,
    rdRowNumConverted: 7,
    rdBasePrice: 200,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field C6",
    r: "3",
    q: "4",
    p: "419",
    i: "VB11775551523",
    d: "3006",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field C6",
    g: "0",
    e: "0",
    h: "03/14/25",
    t: "0",
    v: "2,4",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "378.02",
    mar: false,
    integrated: false,
    bid: "21990",
    dsc: "56.52",
    ls: "11",
    hs: "14",
    faceValue: "201.50",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "448.75",
      aip: "540.25",
      dsc: "80.78",
      faceValue: "287.97",
    },
    op: 314,
    b: 118,
    pOrig: "419",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 314,
    rdRowNumConverted: 3,
    rdBasePrice: 314,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A3",
    r: "28",
    q: "4",
    p: "489",
    i: "VB11749696640",
    d: "1003",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A3",
    g: "0",
    e: "0",
    h: "03/15/25",
    t: "1",
    v: "1,2,3,4",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "442.92",
    mar: false,
    integrated: false,
    bid: "28406",
    dsc: "66.42",
    ls: "*",
    hs: "*",
    faceValue: "0.00",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "527.36",
      aip: "633.00",
      dsc: "94.92",
      faceValue: "0.00",
    },
    op: 369,
    b: 137,
    pOrig: "489",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 885.6,
    rdRowNumConverted: 28,
    rdBasePrice: 369,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A6",
    r: "20",
    q: "5",
    p: "869",
    i: "VB11749213790",
    d: "1006",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A6",
    g: "0",
    e: "0",
    h: "03/15/25",
    t: "1",
    v: "1,2,3,4,5",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "785.12",
    mar: false,
    integrated: false,
    bid: "28406",
    dsc: "118.62",
    ls: "*",
    hs: "*",
    faceValue: "778.50",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "941.81",
      aip: "1122.06",
      dsc: "169.53",
      faceValue: "1112.60",
    },
    op: 659,
    b: 244,
    pOrig: "869",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 1318,
    rdRowNumConverted: 20,
    rdBasePrice: 659,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A5",
    r: "21",
    q: "5",
    p: "919",
    i: "VB11749696635",
    d: "1005",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A5",
    g: "0",
    e: "0",
    h: "03/15/25",
    t: "1",
    v: "1,2,3,4,5",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "833.50",
    mar: false,
    integrated: false,
    bid: "28406",
    dsc: "126.00",
    ls: "*",
    hs: "*",
    faceValue: "827.40",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "1000.41",
      aip: "1191.20",
      dsc: "180.07",
      faceValue: "1182.48",
    },
    op: 700,
    b: 258,
    pOrig: "919",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 1435,
    rdRowNumConverted: 21,
    rdBasePrice: 700,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A7",
    r: "6",
    q: "8",
    p: "979",
    i: "VB11784359456",
    d: "1007",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A7",
    g: "0",
    e: "0",
    h: "03/10/25",
    t: "1",
    v: "1,2,3,4,5,6,7,8",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "880.70",
    mar: false,
    integrated: false,
    bid: "26445",
    dsc: "133.20",
    ls: "",
    hs: "",
    faceValue: "0.00",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "1057.57",
      aip: "1258.66",
      dsc: "190.36",
      faceValue: "0.00",
    },
    op: 740,
    b: 275,
    pOrig: "979",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 962,
    rdRowNumConverted: 6,
    rdBasePrice: 740,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A6",
    r: "6",
    q: "8",
    p: "1109",
    i: "VB11749696627",
    d: "1006",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A6",
    g: "0",
    e: "0",
    h: "03/15/25",
    t: "1",
    v: "1,2,3,4,5,6,7,8",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "1003.42",
    mar: false,
    integrated: false,
    bid: "28406",
    dsc: "151.92",
    ls: "*",
    hs: "*",
    faceValue: "0.00",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "1206.21",
      aip: "1434.04",
      dsc: "217.12",
      faceValue: "0.00",
    },
    op: 844,
    b: 311,
    pOrig: "1109",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 1097.2,
    rdRowNumConverted: 6,
    rdBasePrice: 844,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A3",
    r: "1",
    q: "4",
    p: "1279",
    i: "VB11412312569",
    d: "1003",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A3",
    g: "0",
    e: "0",
    h: "03/14/25",
    t: "0",
    v: "2,4",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "1154.46",
    mar: false,
    integrated: false,
    bid: "21990",
    dsc: "174.96",
    ls: "9",
    hs: "12",
    faceValue: "516.10",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "1389.14",
      aip: "1649.90",
      dsc: "250.04",
      faceValue: "737.59",
    },
    op: 972,
    b: 359,
    pOrig: "1279",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 972,
    rdRowNumConverted: 1,
    rdBasePrice: 972,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A5",
    r: "3",
    q: "6",
    p: "2279",
    i: "VB11767026336",
    d: "1005",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A5",
    g: "0",
    e: "0",
    h: "03/15/25",
    t: "1",
    v: "1,2,3,4,5,6",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "2055.98",
    mar: false,
    integrated: false,
    bid: "28406",
    dsc: "312.48",
    ls: "*",
    hs: "*",
    faceValue: "0.00",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "2481.01",
      aip: "2938.31",
      dsc: "446.58",
      faceValue: "0.00",
    },
    op: 1736,
    b: 639,
    pOrig: "2279",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 1736,
    rdRowNumConverted: 3,
    rdBasePrice: 1736,
    isGeneralAdmission: false,
    metadata: 0,
  },
  {
    s: "Field A6",
    r: "1",
    q: "8",
    p: "2279",
    i: "VB11784744920",
    d: "1006",
    n: "Please note that you will need to use an iOS or Android mobile device to gain entry to your event.",
    f: "0",
    l: "Field A6",
    g: "0",
    e: "0",
    h: "03/15/25",
    t: "1",
    v: "1,2,3,4,5,6,7,8",
    c: "318533",
    z: "0",
    rhdn: "0",
    ind: "0",
    et: "1",
    instantElectronicTransfer: "0",
    instantFlashSeats: "0",
    st: "1",
    fs: "0",
    msc: "0",
    vs: "",
    sd: "0",
    stp: "Ticketmaster Transfer",
    bsv: "",
    aip: "2055.98",
    mar: false,
    integrated: false,
    bid: "28406",
    dsc: "312.48",
    ls: "*",
    hs: "*",
    faceValue: "0.00",
    di: false,
    fdi: "",
    pdi: "",
    localized: {
      p: "2481.01",
      aip: "2938.31",
      dsc: "446.58",
      faceValue: "0.00",
    },
    op: 1736,
    b: 639,
    pOrig: "2279",
    delivery: 7.5,
    rdSubSection: 1,
    rdAdjustedBasePrice: 1736,
    rdRowNumConverted: 1,
    rdBasePrice: 1736,
    isGeneralAdmission: false,
    metadata: 0,
  },
];

const axios = require("axios");

async function fetchVividSeatsListings() {
  try {
    const response = await axios.get(
      "https://www.vividseats.com/hermes/api/v1/listings?productionId=5297524"
    );
    return response.data.tickets;
  } catch (error) {
    console.error("Error fetching VividSeats listings:", error);
    return [];
  }
}

async function comparePricing() {
  const vividListings = await fetchVividSeatsListings();

  const vividMap = new Map(
    vividListings.map((listing) => [listing.i, listing])
  );

  const priceComparisons = rdmInventory
    .map((rdmListing) => {
      const vividListing = vividMap.get(rdmListing.i);

      if (vividListing) {
        const priceDiff = rdmListing.p - vividListing.p;
        const percentDiff = ((priceDiff / vividListing.p) * 100).toFixed(2);

        return {
          identifier: rdmListing.i,
          section: rdmListing.s,
          row: rdmListing.r,
          rdmPrice: rdmListing.p,
          vividPrice: vividListing.p,
          priceDifference: priceDiff,
          percentageDifference: `${percentDiff}%`,
        };
      }
      return null;
    })
    .filter(Boolean);

  return priceComparisons;
}

// Call the comparison function and log results
comparePricing()
  .then((comparisons) => {
    console.log("Price Comparisons:");
    console.log(comparisons);
  })
  .catch((error) => {
    console.error("Error comparing prices:", error);
  });
